### ISSUE TITLE
<h1>Not Found</h1>

### ISSUE THREAD

**Issue by MartinDelille** [jcs/bitwarden-ruby#11]
After running the server with `env RACK_ENV=production bundle exec rackup -p 4567 config.ru` and connecting to `127.0.0.1:4567`, I only get `<h1>Not Found</h1>`...

**Comment by jcs** [comment]
That's expected, there is no root route.  There is nothing to view in a web browser, since this is just an API server.

**Comment by MartinDelille** [comment]
Ok sorry for that I misunderstood. Since my point is to perform a _1Password_ import, how do I create my initial user account with `bitwarden-ruby`?

**Comment by jcs** [comment]
You can use the Bitwarden Firefox or Chrome extension.  Before logging in, click the settings icon in it and set a custom server URL of http://127.0.0.1:4567/
