### ISSUE TITLE
Fields under sections didn't gets imported correctly (1password)

### ISSUE THREAD

**Issue by shouya** [jcs/bitwarden-ruby#16]
Hi,

In the 1password export file (1pif), each entry has the structure that includes something like:

```ruby
{
  secureContents: {
    fields: [*1],
    sections: [{
      fields: [*2],
      title: "<section title>"
    }, ...]
  }
}
```

In which `*1` fields have structures like:

```ruby
{
  name: "username/password/etc",
  value: "xxx"
}
```

and `*2` fields have structures like:

```ruby
{
  "k":"concealed/string",
  "n": "<some hex code>",
  "v": "<the value>",
  "t": "<the title of the field>"
}
```

Type `*2` fields can actually contain 2FA secrets and other important information/password.

While currently the `1password_import.rb` script doesn't import type `*2` fields. `*1` fields are handled [correctly as custom fields](https://github.com/jcs/bitwarden-ruby/blob/master/tools/1password_import.rb#L194) though. I wonder why isn't all type `*1` and `*2` fields both processed as custom fields.

If the current behavior isn't intended, I'd be glad to add support for the type `*2` fields. Please let me know :-)

**Comment by jcs** [comment]
I don't think it was intended.  My concern about importing extra fields was that sometimes 1Password had all of the original signup form fields included there, which often included passwords which then show up in clear text in the Bitwarden app.
