### ISSUE TITLE
Support Delete selected functionality

### ISSUE THREAD

**Issue by mprasil** [jcs/bitwarden-ruby#28]
This one should be fairly easy to implement, might give it a go sometimes later myself.
The `POST` request is sent to `/api/ciphers/delete`

Post data is just list of ids:
```json
{"ids":["214081c5-8a00-4e42-811b-fa0b510cf57e","438410c6a-c5a7-473b-9ab5-ffda741d6811"]}
```

**Comment by universal** [comment]
Hmm... is the request originating from the web-vault? Curious because the chrome-plugin sends ```DELETE /ciphers/:uuid``` for example, and the web-vault: ```POST /ciphers/:uuid```

But yes, the implementation should be fairly straightforward.

**Comment by mprasil** [comment]
Oh yeah, forgot to mention that it's from web-vault. I'm actually using your additions branch @universal

**Comment by universal** [comment]
@mprasil: I added support for deleting and moving multiple ciphers to my additions branch. The web-vault doesn't update on deletion of multiple ciphers though, so reloading it afterwards is required... I don't see a difference between the response from the ruby-server, and the official server, so I'm clueless as to why it does not update! It deletes the entries just fine though.

**Comment by mprasil** [comment]
That's perfect, I'm going to give it a try now!
