### ISSUE TITLE
Syncing fails with latest Browser addon

### ISSUE THREAD

**Issue by rmx-it** [jcs/bitwarden-ruby#34]
Hi,
as it seems, the latest firefox addon fails to sync now against bitwarden-ruby.
Maybe API changes upstream?

Greetings
...
Mike

**Comment by raufis27** [comment]
Same problem here. Desktop app works fine.

**Comment by jcs** [comment]
I am working on it, see #32

**Comment by raufis27** [comment]
Thank you!

**Comment by jcs** [comment]
Please see #36 and help test these changes so I can merge them into master.
