### ISSUE TITLE
Folder support

### ISSUE THREAD

**Issue by papertigers** [jcs/bitwarden-ruby#4]
Have you looked at how hard folder support would be?  Started messing around with this project today. Thanks for doing this work!

**Comment by jcs** [comment]
It's [already there](https://github.com/jcs/bitwarden-ruby/commit/2ecd4e9eb35124205b3203bee7943a15bc02657c), is it not working for you?

**Comment by papertigers** [comment]
Hmm I tried from the iOS app. I haven’t had a chance to debug yet but here’s the log

__IP__ - - [19/Nov/2017:23:49:32 +0000] "POST /apifolders HTTP/1.1" 404 18 0.0013

**Comment by jcs** [comment]
Hmm, looks like it dropped a slash between `api` and `folders` somehow.  Did you just set one URL for your private instance in the iOS app or did you fill in all 3?

**Comment by papertigers** [comment]
I only set one URL up in the app.

**Comment by jcs** [comment]
Ah, I get the same error from the iOS app.  I think this is a bug in the app, because folder creation/deletion works fine from the Firefox extension.

**Comment by papertigers** [comment]
Ahh thanks. Sorry to bug you for no reason. 

PS are you leaving your service exposed publicly or are you keeping it only on an internal LAN etc?

**Comment by jcs** [comment]
No problem.  I'll leave this open to track when this gets fixed [upstream](https://github.com/bitwarden/mobile) (if you could file a bug there, that'd be great).

Mine is exposed publicly, which is one of the main reasons I wanted to write a small server instead of all the .NET stuff.

**Comment by papertigers** [comment]
Filed: https://github.com/bitwarden/mobile/issues/174

**Comment by jcs** [comment]
@kspearrin quickly fixed that upstream, so I'm going to close this.
