### ISSUE TITLE
Mac OS desktop add doesn't work

### ISSUE THREAD

**Issue by raufis27** [jcs/bitwarden-ruby#40]
Should we wait for update from bitwarden or this is something you have to fix ?

**Comment by jcs** [comment]
It's working for me with the latest changes in #36, are you using version 1.1.0 of the macOS app?

**Comment by raufis27** [comment]
I just downloaded latest available app from website and it is 1.0.5. How did you update ?

**Comment by raufis27** [comment]
Oh I see, App Store has latest, but website doesn't.

**Comment by jcs** [comment]
@kspearrin

**Comment by raufis27** [comment]
1.1.0 Works fine. Thank you.

**Comment by jcs** [comment]
You may want to file an issue on the upstream @bitwarden repos to update the download link to 1.1.0.

**Comment by kspearrin** [comment]
Download links are updated. Thanks.
