### ISSUE TITLE
iOS 'problem with connecting to the server'

### ISSUE THREAD

**Issue by lorddusk** [jcs/bitwarden-ruby#50]
I can connect to the server with all browser extensions, android application and desktop application. But if I want to connect with my iPhone, it tells me that it has a problem with connecting to the server.
I can't see anything in the running console.

Anything I can do to make this work?

**Comment by universal** [comment]
Hmm, this is weird. I'm also using the app on an iPhone, and it works just fine. I'm using the additions branch from my fork though, so maybe the addition of the web-vault compatibility helps? You can check the requests and responses by adding a custom logger (see this commit for details: https://github.com/universal/bitwarden-ruby/commit/8341e594506346537e1c01c2b575d3e915497845). 

Maybe this already shows why it is not working.

**Comment by lorddusk** [comment]
@universal I tried running your additions fork, but it wasn't compatible with the database I created in the normal branch.

**Comment by universal** [comment]
@lorddusk does it work for you now? Using my active-record(-additions) branch it works for me.

**Comment by lorddusk** [comment]
@universal I will check asap, will get back to you later today (CEST)
