### ISSUE TITLE
Keepass Import error 'read_header'

### ISSUE THREAD

**Issue by mannp** [jcs/bitwarden-ruby#54]
Thanks for creating this.

I have got things running in a docker and 2FA works, but trying to import keepass directly fails with the following error;

> /usr/local/bundle/gems/rubeepass-3.0.0/lib/rubeepass.rb:404:in `read_header': undefined method `length' for nil:NilClass (NoMethodError)
> 	from /usr/local/bundle/gems/rubeepass-3.0.0/lib/rubeepass.rb:450:in `start_opening'
> 	from /usr/local/bundle/gems/rubeepass-3.0.0/lib/rubeepass.rb:277:in `open'
> 	from tools/keepass_import.rb:118:in `<main>'

It asks for my password and then errors immediately.

Database is Argon2 AES 256.

Thanks in advance

**Comment by jcs** [comment]
From the [`rubeepass` code](https://gitlab.com/mjwhitta/rubeepass/blob/master/lib/rubeepass.rb#L404), it looks like it failed reading your database file.  I would try opening an issue there since all of the Keepass reading is done by that gem.
