### ISSUE TITLE
Bad Request-Line and bad URI errors on account creation

### ISSUE THREAD

**Issue by parski** [jcs/bitwarden-ruby#57]
I'm having some trouble setting up this service in a FreeNAS 11.1 jail. It's a fresh jail that I haven't tampered with apart from creating a user for bitwarden, installing RVM and with it Ruby 2.4.1. First I tried to use the port of this service but it appears to be outdated and a test was failing so I decided to clone the repo instead. Now all the tests are passing:
```
[bitwarden@bitwarden /usr/local/www/bitwarden-ruby]$ bundle exec rake test --trace
** Invoke test (first_time)
** Execute test
/usr/local/www/bitwarden-ruby/lib/bitwarden_ruby.rb:17: warning: setting Encoding.default_external
/usr/local/www/bitwarden-ruby/lib/bitwarden_ruby.rb:17: warning: setting Encoding.default_internal
migrating db from version 0
/usr/local/www/bitwarden-ruby/lib/dbmodel.rb:65: warning: instance variable @columns not initialized
/usr/local/www/bitwarden-ruby/lib/dbmodel.rb:65: warning: instance variable @columns not initialized
/usr/local/www/bitwarden-ruby/lib/dbmodel.rb:65: warning: instance variable @columns not initialized
/usr/local/www/bitwarden-ruby/lib/dbmodel.rb:65: warning: instance variable @columns not initialized
Run options: --seed 46684

# Running:

.......................

Finished in 4.791403s, 4.8003 runs/s, 15.2356 assertions/s.

23 runs, 73 assertions, 0 failures, 0 errors, 0 skips
```

Looks great. Now I run the service:

```
[bitwarden@bitwarden /usr/local/www/bitwarden-ruby]$ env RACK_ENV=production ALLOW_SIGNUPS=1 bundle exec rackup -p 4567 config.ru
migrating db from version 0
[2018-07-04 23:44:20] INFO  WEBrick 1.3.1
[2018-07-04 23:44:20] INFO  ruby 2.4.1 (2017-03-22) [x86_64-freebsd11.1]
[2018-07-04 23:44:20] INFO  WEBrick::HTTPServer#start: pid=61867 port=4567
```
Still looks great. Now if I try to create an account I get the following:
```
[2018-07-04 23:44:28] ERROR bad Request-Line `\x16\x03\x01\x00▒\x01\x00\x00▒\x03\x03▒▒J▒\x054▒t5ݽ"▒S▒▒\x1C`▒▒▒\x1C▒▒▒▒3UDΨb\x00\x00(▒,▒+▒$▒#▒'.
[2018-07-04 23:44:28] ERROR bad URI `r▒▒,▒U▒▒\x05▒▒x▒TaH▒▒є▒▒▒!▒▒▒\x0F\x00\x00.▒,▒+▒$▒#▒'.
[2018-07-04 23:44:28] ERROR bad URI `▒'.
```
I've tried to create an account via the Bitwarden provided iOS app as well as the Firefox extension but I keep getting these errors.

I thought it might be an encoding issue (I'm still not convinced it isn't) but my `$LANG` is `en_US.UTF-8` and `bitwarden_ruby.rb` seems to be setting everything to UTF-8 as well judging by:
```
Encoding.default_internal = Encoding.default_external = Encoding::UTF_8
```
That said I'm not very fluent in Ruby.

Anyone have a clue what the problem might be?

**Comment by jcs** [comment]
Are you accessing the rack instance (on port 4567) directly or do you have a server in front of it like nginx?

**Comment by parski** [comment]
I guess FreeNAS could be doing some proxying with nginx but in that case I haven't configured it, it's a pretty much out of the box installation. I've just specified the IP of the jail followed by the port in the clients.

**Comment by jcs** [comment]
Are your Bitwarden apps trying to talk to your server over https?

**Comment by parski** [comment]
Both clients went ahead and silently added `https://` after saving the configuration. I suppose that's a good thing and I'm ashamed for not specifying it with `http://` before setting up TLS/SSL on the server.

Thanks for the help and I'm sorry to have bothered you. I'm looking forward to trying your service, it seems great!
