### ISSUE TITLE
README concern about key usage

### ISSUE THREAD

**Issue by kspearrin** [jcs/bitwarden-ruby#6]
I noticed the following in your README:

> All items must be re-encrypted server-side if your master password or e-mail address change (not yet supported).

This is inaccurate. Since the introduction of `User.Key` (generated 512 bit symmetric key) all items are encrypted with `AesCbc256_HmacSha256_B64`. The unencrypted version of the generated symmetric key never changes and is generated client-side at the time of account creation. If a user changes their master password, only the master key (via PBKDF2) changes and the generated symmetric key value is re-encrypted (but not changed). Because the generated symmetric key doesn't change, no vault items have to be re-encrypted.

I just want to ensure that you are not using the encryption type of `AesCbc256_B64` from the master key for items in your vault. `AesCbc256_B64` should only be used to encrypt the 512 bit generated symmetric key with the 256 bit master key.

For more info on bitwarden crypto see: https://help.bitwarden.com/crypto.html

**Comment by jcs** [comment]
Thanks, I've updated the documentation to use the same terminology for each key as your site does.  My code was using `AesCbc256_HmacSha256_B64` for Cipher items (though it only ever encrypted/decrypted things server-side in the 1Password conversion) properly.

While I have you here, can you explain what the RSA keypair is used for, and is that what is returned from the identity server as `PrivateKey`?  And what is `TwoFactorToken` returned by the identity server?

**Comment by kspearrin** [comment]
They keypair is used for the sharing features, which it seems you have not implemented. Feel free to ignore them. `PrivateKey` is the encrypted RSA private key. See the crypto app above.

`TwoFactorToken` is used when using "remember me" for 2FA. You can pass the returned `TwoFactorToken` next time and skip having to enter your TOTP again for example.

**Comment by jcs** [comment]
Thanks!
